version: '3.8'

services:
  metube:
    build: .
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
    environment:
      - UID=1000
      - GID=1000
      - DOWNLOAD_DIR=/downloads
      - YTDL_OPTIONS_FILE=/app/ytdl_config.json
      - LOGLEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/version"]
      interval: 30s
      timeout: 10s
      retries: 3
